# Generated by Django 4.2 on 2023-05-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="client_status",
        ),
        migrations.AddField(
            model_name="client",
            name="under_contract",
            field=models.BooleanField(default=False),
        ),
    ]
