# Generated by Django 4.2 on 2023-04-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_alter_user_first_name_alter_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(),
        ),
    ]
