# Generated by Django 4.2 on 2023-04-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0003_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="mobile",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.IntegerField(unique=True),
        ),
    ]
