# Generated by Django 4.2 on 2023-05-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0004_alter_client_mobile_alter_client_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="mobile",
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="payment_due",
            field=models.DateField(),
        ),
    ]
