# Generated by Django 4.2 on 2023-05-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0005_alter_client_mobile_alter_client_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_status",
            field=models.BooleanField(default=False, verbose_name="Under contract"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Signed"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_status",
            field=models.CharField(
                choices=[("COMING", "Coming"), ("DONE", "done")], max_length=20
            ),
        ),
    ]
